name: collective_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.11
  - ffmpeg
  - jupyterlab
  - ipykernel
  - matplotlib
  - graph-tool
  - tqdm
  - numpy
  - scipy
  - pip
  - pip:
    - ray[rllib]
    - torch
    - "wandb[media]"
    - ipywidgets
    - jupyterlab-execute-time
    - opencv-python