name: collective_env
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - ffmpeg
  - jupyterlab
  - matplotlib
  - tqdm
  - graph-tool
  - pip
  - pip:
    - ray[rllib]
    - gymnasium
    - numpy
    - torch
    - wandb
    - ipywidgets
    - jupyterlab-execute-time