name: collective_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - ffmpeg
  - jupyterlab
  - matplotlib
  - graph-tool
  - pip
  - pip:
    - ray[default, rllib]
    - gymnasium
    - numpy
    - tensorflow
    #- tensorflow-metal # [osx] # doesn't seem to work
    - torch
    - wandb
    - ipywidgets